# Generated by Django 6.0.4 on 2026-04-22 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SponsorshipPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(help_text='Describe the impact of this plan')),
                ('amount', models.PositiveIntegerField(help_text='Suggested amount in INR')),
            ],
        ),
    ]
